# Generated by Django 2.2.6 on 2019-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runtracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=0, max_digits=6)),
                ('time', models.DecimalField(decimal_places=0, max_digits=6)),
                ('calories', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
